import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { IonicModule } from '@ionic/angular';

@Component({
  selector: 'app-phone-numbers',
  templateUrl: './phone-numbers.page.html',
  styleUrls: ['./phone-numbers.page.scss'],
  standalone: true,
  imports: [IonicModule, CommonModule, FormsModule]
})
export class PhoneNumbersPage implements OnInit {
    phoneNumbers = [
    { text: '🇺🇸 +1   United States', code: '+1', country: 'US' },
    { text: '🇨🇦 +1   Canada', code: '+1', country: 'CA' },
    { text: '🇷🇺 +7   Russia', code: '+7', country: 'RU' },
    { text: '🇪🇬 +20  Egypt', code: '+20', country: 'EG' },
    { text: '🇿🇦 +27  South Africa', code: '+27', country: 'ZA' },
    { text: '🇬🇷 +30  Greece', code: '+30', country: 'GR' },
    { text: '🇳🇱 +31  Netherlands', code: '+31', country: 'NL' },
    { text: '🇧🇪 +32  Belgium', code: '+32', country: 'BE' },
    { text: '🇫🇷 +33  France', code: '+33', country: 'FR' },
    { text: '🇪🇸 +34  Spain', code: '+34', country: 'ES' },
    { text: '🇭🇺 +36  Hungary', code: '+36', country: 'HU' },
    { text: '🇮🇹 +39  Italy', code: '+39', country: 'IT' },
    { text: '🇷🇴 +40  Romania', code: '+40', country: 'RO' },
    { text: '🇨🇭 +41  Switzerland', code: '+41', country: 'CH' },
    { text: '🇦🇹 +43  Austria', code: '+43', country: 'AT' },
    { text: '🇬🇧 +44  United Kingdom', code: '+44', country: 'GB' },
    { text: '🇩🇰 +45  Denmark', code: '+45', country: 'DK' },
    { text: '🇸🇪 +46  Sweden', code: '+46', country: 'SE' },
    { text: '🇳🇴 +47  Norway', code: '+47', country: 'NO' },
    { text: '🇵🇱 +48  Poland', code: '+48', country: 'PL' },
    { text: '🇩🇪 +49  Germany', code: '+49', country: 'DE' },
    { text: '🇵🇪 +51  Peru', code: '+51', country: 'PE' },
    { text: '🇲🇽 +52  Mexico', code: '+52', country: 'MX' },
    { text: '🇨🇺 +53  Cuba', code: '+53', country: 'CU' },
    { text: '🇦🇷 +54  Argentina', code: '+54', country: 'AR' },
    { text: '🇧🇷 +55  Brazil', code: '+55', country: 'BR' },
    { text: '🇨🇱 +56  Chile', code: '+56', country: 'CL' },
    { text: '🇨🇴 +57  Colombia', code: '+57', country: 'CO' },
    { text: '🇻🇪 +58  Venezuela', code: '+58', country: 'VE' },
    { text: '🇲🇾 +60  Malaysia', code: '+60', country: 'MY' },
    { text: '🇦🇺 +61  Australia', code: '+61', country: 'AU' },
    { text: '🇮🇩 +62  Indonesia', code: '+62', country: 'ID' },
    { text: '🇵🇭 +63  Philippines', code: '+63', country: 'PH' },
    { text: '🇳🇿 +64  New Zealand', code: '+64', country: 'NZ' },
    { text: '🇸🇬 +65  Singapore', code: '+65', country: 'SG' },
    { text: '🇹🇭 +66  Thailand', code: '+66', country: 'TH' },
    { text: '🇯🇵 +81  Japan', code: '+81', country: 'JP' },
    { text: '🇰🇷 +82  South Korea', code: '+82', country: 'KR' },
    { text: '🇻🇳 +84  Vietnam', code: '+84', country: 'VN' },
    { text: '🇨🇳 +86  China', code: '+86', country: 'CN' },
    { text: '🇹🇷 +90  Turkey', code: '+90', country: 'TR' },
    { text: '🇮🇳 +91  India', code: '+91', country: 'IN' },
    { text: '🇵🇰 +92  Pakistan', code: '+92', country: 'PK' },
    { text: '🇦🇫 +93  Afghanistan', code: '+93', country: 'AF' },
    { text: '🇱🇰 +94  Sri Lanka', code: '+94', country: 'LK' },
    { text: '🇲🇲 +95  Myanmar', code: '+95', country: 'MM' },
    { text: '🇮🇷 +98  Iran', code: '+98', country: 'IR' },
    { text: '🇲🇦 +212 Morocco', code: '+212', country: 'MA' },
    { text: '🇩🇿 +213 Algeria', code: '+213', country: 'DZ' },
    { text: '🇹🇳 +216 Tunisia', code: '+216', country: 'TN' },
    { text: '🇱🇾 +218 Libya', code: '+218', country: 'LY' },
    { text: '🇬🇲 +220 Gambia', code: '+220', country: 'GM' },
    { text: '🇸🇳 +221 Senegal', code: '+221', country: 'SN' },
    { text: '🇲🇷 +222 Mauritania', code: '+222', country: 'MR' },
    { text: '🇲🇱 +223 Mali', code: '+223', country: 'ML' },
    { text: '🇬🇳 +224 Guinea', code: '+224', country: 'GN' },
    { text: '🇨🇮 +225 Ivory Coast', code: '+225', country: 'CI' },
    { text: '🇧🇫 +226 Burkina Faso', code: '+226', country: 'BF' },
    { text: '🇳🇪 +227 Niger', code: '+227', country: 'NE' },
    { text: '🇹🇬 +228 Togo', code: '+228', country: 'TG' },
    { text: '🇧🇯 +229 Benin', code: '+229', country: 'BJ' },
    { text: '🇲🇺 +230 Mauritius', code: '+230', country: 'MU' },
    { text: '🇱🇷 +231 Liberia', code: '+231', country: 'LR' },
    { text: '🇸🇱 +232 Sierra Leone', code: '+232', country: 'SL' },
    { text: '🇬🇭 +233 Ghana', code: '+233', country: 'GH' },
    { text: '🇳🇬 +234 Nigeria', code: '+234', country: 'NG' },
    { text: '🇹🇩 +235 Chad', code: '+235', country: 'TD' },
    { text: '🇨🇫 +236 Central African Republic', code: '+236', country: 'CF' },
    { text: '🇨🇲 +237 Cameroon', code: '+237', country: 'CM' },
    { text: '🇨🇻 +238 Cape Verde', code: '+238', country: 'CV' },
    { text: '🇸🇹 +239 Sao Tome and Principe', code: '+239', country: 'ST' },
    { text: '🇬🇶 +240 Equatorial Guinea', code: '+240', country: 'GQ' },
    { text: '🇬🇦 +241 Gabon', code: '+241', country: 'GA' },
    { text: '🇨🇬 +242 Republic of the Congo', code: '+242', country: 'CG' },
    { text: '🇨🇩 +243 Democratic Republic of the Congo', code: '+243', country: 'CD' },
    { text: '🇦🇴 +244 Angola', code: '+244', country: 'AO' },
    { text: '🇬🇼 +245 Guinea-Bissau', code: '+245', country: 'GW' },
    { text: '🇮🇴 +246 British Indian Ocean Territory', code: '+246', country: 'IO' },
    { text: '🇸🇨 +248 Seychelles', code: '+248', country: 'SC' },
    { text: '🇸🇩 +249 Sudan', code: '+249', country: 'SD' },
    { text: '🇷🇼 +250 Rwanda', code: '+250', country: 'RW' },
    { text: '🇪🇹 +251 Ethiopia', code: '+251', country: 'ET' },
    { text: '🇸🇴 +252 Somalia', code: '+252', country: 'SO' },
    { text: '🇩🇯 +253 Djibouti', code: '+253', country: 'DJ' },
    { text: '🇰🇪 +254 Kenya', code: '+254', country: 'KE' },
    { text: '🇹🇿 +255 Tanzania', code: '+255', country: 'TZ' },
    { text: '🇺🇬 +256 Uganda', code: '+256', country: 'UG' },
    { text: '🇧🇮 +257 Burundi', code: '+257', country: 'BI' },
    { text: '🇲🇿 +258 Mozambique', code: '+258', country: 'MZ' },
    { text: '🇿🇲 +260 Zambia', code: '+260', country: 'ZM' },
    { text: '🇲🇬 +261 Madagascar', code: '+261', country: 'MG' },
    { text: '🇷🇪 +262 Reunion', code: '+262', country: 'RE' },
    { text: '🇿🇼 +263 Zimbabwe', code: '+263', country: 'ZW' },
    { text: '🇳🇦 +264 Namibia', code: '+264', country: 'NA' },
    { text: '🇲🇼 +265 Malawi', code: '+265', country: 'MW' },
    { text: '🇱🇸 +266 Lesotho', code: '+266', country: 'LS' },
    { text: '🇧🇼 +267 Botswana', code: '+267', country: 'BW' },
    { text: '🇸🇿 +268 Eswatini', code: '+268', country: 'SZ' },
    { text: '🇰🇲 +269 Comoros', code: '+269', country: 'KM' },
    { text: '🇮🇱 +972 Israel', code: '+972', country: 'IL' },
    { text: '🇧🇭 +973 Bahrain', code: '+973', country: 'BH' },
    { text: '🇶🇦 +974 Qatar', code: '+974', country: 'QA' },
    { text: '🇧🇹 +975 Bhutan', code: '+975', country: 'BT' },
    { text: '🇲🇳 +976 Mongolia', code: '+976', country: 'MN' },
    { text: '🇳🇵 +977 Nepal', code: '+977', country: 'NP' },
    { text: '🇹🇯 +992 Tajikistan', code: '+992', country: 'TJ' },
    { text: '🇹🇲 +993 Turkmenistan', code: '+993', country: 'TM' },
    { text: '🇦🇿 +994 Azerbaijan', code: '+994', country: 'AZ' },
    { text: '🇬🇪 +995 Georgia', code: '+995', country: 'GE' },
    { text: '🇰🇬 +996 Kyrgyzstan', code: '+996', country: 'KG' },
    { text: '🇺🇿 +998 Uzbekistan', code: '+998', country: 'UZ' },
]
  constructor() { }

  ngOnInit() {
  }

}
